[package]
name = "ssm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

# -- Binaries --
[[bin]]
name = "ssm"
path = "src/ssm.rs"

[[bin]]
name = "ssmasm"
path = "src/ssmasm.rs"