// Generated by /opcode/cgen.rb
// If this file is modified, please add a comment


#include <stdint.h>

typedef struct OpHeader {
  uint32_t version;
  uint32_t chunk_size;
  uint32_t global_offset;
  uint32_t global_count;
} OpHeader;

int readOpHeader(OpHeader *header, const uint8_t *ip) {
  // Check opcode is correct
  if(ip[0] != SSM_OP_HEADER) return 0;
  // Read header
  header->version = read_uint32_t(ip + 1);
  header->chunk_size = read_uint32_t(ip + 5);
  header->global_offset = read_uint32_t(ip + 9);
  header->global_count = read_uint32_t(ip + 13);
  return 1;
}
