// Generated by /opcode/cgen.rb
// If this file is modified, please add a comment


OP(NOP) {
  unimplemented();
  NEXT(1);
}
OP(POP) {
  register uint16_t count = read_uint16_t(ip + 1);
  unimplemented();
  NEXT(3);
}
OP(PUSH) {
  register uint16_t off = read_uint16_t(ip + 1);
  unimplemented();
  NEXT(3);
}
OP(PUSHBP) {
  register uint16_t off_bp = read_uint16_t(ip + 1);
  unimplemented();
  NEXT(3);
}
OP(PUSHAP) {
  register uint16_t off_ap = read_uint16_t(ip + 1);
  unimplemented();
  NEXT(3);
}
OP(POPSET) {
  register uint16_t off_sp = read_uint16_t(ip + 1);
  unimplemented();
  NEXT(3);
}
OP(PUSHI) {
  register int32_t value = read_int32_t(ip + 1);
  unimplemented();
  NEXT(5);
}
OP(PUSHF) {
  register float32_t value = read_float32_t(ip + 1);
  unimplemented();
  NEXT(5);
}
OP(PUSHFN) {
  register int32_t fn_off = read_int32_t(ip + 1);
  unimplemented();
  NEXT(5);
}
OP(PUSHGLOBAL) {
  register uint32_t index = read_uint32_t(ip + 1);
  unimplemented();
  NEXT(5);
}
OP(POPSETGLOBAL) {
  register uint32_t index = read_uint32_t(ip + 1);
  unimplemented();
  NEXT(5);
}
OP(PUSHISLONG) {
  register uint16_t off = read_uint16_t(ip + 1);
  unimplemented();
  NEXT(3);
}
OP(TUP) {
  register uint16_t tag = read_uint16_t(ip + 1);
  register uint16_t count = read_uint16_t(ip + 3);
  unimplemented();
  NEXT(5);
}
OP(PUSHTAG) {
  register uint16_t off = read_uint16_t(ip + 1);
  unimplemented();
  NEXT(3);
}
OP(PUSHLEN) {
  register uint16_t off = read_uint16_t(ip + 1);
  unimplemented();
  NEXT(3);
}
OP(PUSHELEM) {
  register uint16_t off = read_uint16_t(ip + 1);
  register uint16_t index = read_uint16_t(ip + 3);
  unimplemented();
  NEXT(5);
}
OP(LONG) {
  register uint32_t bytes_len = read_uint32_t(ip + 1);
  register uint8_t* bytes = (uint8_t*)(ip + 5);
  // Use read_uint8_t(&bytes + IDX) to get elements
  unimplemented();
  NEXT(5 + bytes_len * sizeof(uint8_t));
}
OP(POPSETBYTE) {
  register uint16_t off = read_uint16_t(ip + 1);
  unimplemented();
  NEXT(3);
}
OP(PUSHLONGLEN) {
  register uint16_t off = read_uint16_t(ip + 1);
  unimplemented();
  NEXT(3);
}
OP(PUSHBYTE) {
  register uint16_t off = read_uint16_t(ip + 1);
  unimplemented();
  NEXT(3);
}
OP(JOIN) {
  unimplemented();
  NEXT(1);
}
OP(SUBLONG) {
  unimplemented();
  NEXT(1);
}
OP(LONGCMP) {
  unimplemented();
  NEXT(1);
}
OP(APP) {
  register uint16_t count = read_uint16_t(ip + 1);
  unimplemented();
  NEXT(3);
}
OP(RET) {
  register uint16_t off = read_uint16_t(ip + 1);
  unimplemented();
  NEXT(3);
}
OP(RETAPP) {
  register uint16_t count = read_uint16_t(ip + 1);
  unimplemented();
  NEXT(3);
}
OP(INTADD) {
  unimplemented();
  NEXT(1);
}
OP(INTSUB) {
  unimplemented();
  NEXT(1);
}
OP(INTMUL) {
  unimplemented();
  NEXT(1);
}
OP(UINTMUL) {
  unimplemented();
  NEXT(1);
}
OP(INTDIV) {
  unimplemented();
  NEXT(1);
}
OP(UINTDIV) {
  unimplemented();
  NEXT(1);
}
OP(INTMOD) {
  unimplemented();
  NEXT(1);
}
OP(UINTMOD) {
  unimplemented();
  NEXT(1);
}
OP(INTUNM) {
  unimplemented();
  NEXT(1);
}
OP(INTSHL) {
  unimplemented();
  NEXT(1);
}
OP(INTSHR) {
  unimplemented();
  NEXT(1);
}
OP(UINTSHR) {
  unimplemented();
  NEXT(1);
}
OP(INTAND) {
  unimplemented();
  NEXT(1);
}
OP(INTOR) {
  unimplemented();
  NEXT(1);
}
OP(INTXOR) {
  unimplemented();
  NEXT(1);
}
OP(INTNEG) {
  unimplemented();
  NEXT(1);
}
OP(INTLT) {
  unimplemented();
  NEXT(1);
}
OP(INTLE) {
  unimplemented();
  NEXT(1);
}
OP(FLOATADD) {
  unimplemented();
  NEXT(1);
}
OP(FLOATSUB) {
  unimplemented();
  NEXT(1);
}
OP(FLOATMUL) {
  unimplemented();
  NEXT(1);
}
OP(FLOATDIV) {
  unimplemented();
  NEXT(1);
}
OP(FLOATUNM) {
  unimplemented();
  NEXT(1);
}
OP(FLOATLT) {
  unimplemented();
  NEXT(1);
}
OP(FLOATLE) {
  unimplemented();
  NEXT(1);
}
OP(EQ) {
  unimplemented();
  NEXT(1);
}
OP(NE) {
  unimplemented();
  NEXT(1);
}
OP(JMP) {
  register int32_t off = read_int32_t(ip + 1);
  unimplemented();
  NEXT(5);
}
OP(BEZ) {
  register int16_t off = read_int16_t(ip + 1);
  unimplemented();
  NEXT(3);
}
OP(BNE) {
  register int16_t off = read_int16_t(ip + 1);
  unimplemented();
  NEXT(3);
}
OP(BTAG) {
  register uint16_t tag = read_uint16_t(ip + 1);
  register int16_t off = read_int16_t(ip + 3);
  unimplemented();
  NEXT(5);
}
OP(JTAG) {
  register uint32_t jump_table_len = read_uint32_t(ip + 1);
  register int32_t* jump_table = (int32_t*)(ip + 5);
  // Use read_int32_t(&jump_table + IDX) to get elements
  unimplemented();
  NEXT(5 + jump_table_len * sizeof(int32_t));
}
OP(MAGIC) {
  // Handle magic
  switch(read_uint16_t(ip + 1)) {
  case SSM_MAGIC_NOP: {
    // nop
    unimplemented();
  } break;
  case SSM_MAGIC_HALT: {
    // halt
    unimplemented();
  } break;
  case SSM_MAGIC_NEWVM: {
    // newvm
    unimplemented();
  } break;
  case SSM_MAGIC_NEWPROCESS: {
    // newprocess
    unimplemented();
  } break;
  case SSM_MAGIC_VMSELF: {
    // vmself
    unimplemented();
  } break;
  case SSM_MAGIC_VMPARENT: {
    // vmparent
    unimplemented();
  } break;
  case SSM_MAGIC_DUP: {
    // dup
    unimplemented();
  } break;
  case SSM_MAGIC_GLOBALC: {
    // globalc
    unimplemented();
  } break;
  case SSM_MAGIC_EXECUTE: {
    // execute
    unimplemented();
  } break;
  case SSM_MAGIC_HALTED: {
    // halted
    unimplemented();
  } break;
  case SSM_MAGIC_SENDMSG: {
    // sendmsg
    unimplemented();
  } break;
  case SSM_MAGIC_HASMSG: {
    // hasmsg
    unimplemented();
  } break;
  case SSM_MAGIC_RECVMSG: {
    // recvmsg
    unimplemented();
  } break;
  case SSM_MAGIC_EVAL: {
    // eval
    unimplemented();
  } break;
  case SSM_MAGIC_FOPEN: {
    // fopen
    unimplemented();
  } break;
  case SSM_MAGIC_FCLOSE: {
    // fclose
    unimplemented();
  } break;
  case SSM_MAGIC_FFLUSH: {
    // fflush
    unimplemented();
  } break;
  case SSM_MAGIC_FREAD: {
    // fread
    unimplemented();
  } break;
  case SSM_MAGIC_FWRITE: {
    // fwrite
    unimplemented();
  } break;
  case SSM_MAGIC_FTELL: {
    // ftell
    unimplemented();
  } break;
  case SSM_MAGIC_FSEEK: {
    // fseek
    unimplemented();
  } break;
  case SSM_MAGIC_FEOF: {
    // feof
    unimplemented();
  } break;
  case SSM_MAGIC_STDREAD: {
    // stdread
    unimplemented();
  } break;
  case SSM_MAGIC_STDWRITE: {
    // stdwrite
    unimplemented();
  } break;
  case SSM_MAGIC_STDERROR: {
    // stderror
    unimplemented();
  } break;
  case SSM_MAGIC_REMOVE: {
    // remove
    unimplemented();
  } break;
  case SSM_MAGIC_RENAME: {
    // rename
    unimplemented();
  } break;
  case SSM_MAGIC_TMPFILE: {
    // tmpfile
    unimplemented();
  } break;
  case SSM_MAGIC_READFILE: {
    // readfile
    unimplemented();
  } break;
  case SSM_MAGIC_WRITEFILE: {
    // writefile
    unimplemented();
  } break;
  case SSM_MAGIC_MALLOC: {
    // malloc
    unimplemented();
  } break;
  case SSM_MAGIC_FREE: {
    // free
    unimplemented();
  } break;
  case SSM_MAGIC_SRAND: {
    // srand
    unimplemented();
  } break;
  case SSM_MAGIC_RAND: {
    // rand
    unimplemented();
  } break;
  case SSM_MAGIC_ARG: {
    // arg
    unimplemented();
  } break;
  case SSM_MAGIC_ENV: {
    // env
    unimplemented();
  } break;
  case SSM_MAGIC_EXIT: {
    // exit
    unimplemented();
  } break;
  case SSM_MAGIC_SYSTEM: {
    // system
    unimplemented();
  } break;
  case SSM_MAGIC_PI: {
    // pi
    unimplemented();
  } break;
  case SSM_MAGIC_E: {
    // e
    unimplemented();
  } break;
  case SSM_MAGIC_ABS: {
    // abs
    unimplemented();
  } break;
  case SSM_MAGIC_SIN: {
    // sin
    unimplemented();
  } break;
  case SSM_MAGIC_COS: {
    // cos
    unimplemented();
  } break;
  case SSM_MAGIC_TAN: {
    // tan
    unimplemented();
  } break;
  case SSM_MAGIC_ASIN: {
    // asin
    unimplemented();
  } break;
  case SSM_MAGIC_ACOS: {
    // acos
    unimplemented();
  } break;
  case SSM_MAGIC_ATAN: {
    // atan
    unimplemented();
  } break;
  case SSM_MAGIC_ATAN2: {
    // atan2
    unimplemented();
  } break;
  case SSM_MAGIC_EXP: {
    // exp
    unimplemented();
  } break;
  case SSM_MAGIC_LOG: {
    // log
    unimplemented();
  } break;
  case SSM_MAGIC_LOG10: {
    // log10
    unimplemented();
  } break;
  case SSM_MAGIC_LN: {
    // ln
    unimplemented();
  } break;
  case SSM_MAGIC_MODF: {
    // modf
    unimplemented();
  } break;
  case SSM_MAGIC_POW: {
    // pow
    unimplemented();
  } break;
  case SSM_MAGIC_SQRT: {
    // sqrt
    unimplemented();
  } break;
  case SSM_MAGIC_CEIL: {
    // ceil
    unimplemented();
  } break;
  case SSM_MAGIC_FLOOR: {
    // floor
    unimplemented();
  } break;
  case SSM_MAGIC_FABS: {
    // fabs
    unimplemented();
  } break;
  case SSM_MAGIC_FMOD: {
    // fmod
    unimplemented();
  } break;
  case SSM_MAGIC_CLOCK: {
    // clock
    unimplemented();
  } break;
  case SSM_MAGIC_TIME: {
    // time
    unimplemented();
  } break;
  case SSM_MAGIC_CWD: {
    // cwd
    unimplemented();
  } break;
  case SSM_MAGIC_ISDIR: {
    // isdir
    unimplemented();
  } break;
  case SSM_MAGIC_ISFILE: {
    // isfile
    unimplemented();
  } break;
  case SSM_MAGIC_MKDIR: {
    // mkdir
    unimplemented();
  } break;
  case SSM_MAGIC_RMDIR: {
    // rmdir
    unimplemented();
  } break;
  case SSM_MAGIC_CHDIR: {
    // chdir
    unimplemented();
  } break;
  case SSM_MAGIC_FILES: {
    // files
    unimplemented();
  } break;
  case SSM_MAGIC_JOINPATH: {
    // joinpath
    unimplemented();
  } break;
  case SSM_MAGIC_FFILOAD: {
    // ffiload
    unimplemented();
  } break;
  case SSM_MAGIC_OS: {
    // os
    unimplemented();
  } break;
  case SSM_MAGIC_ARCH: {
    // arch
    unimplemented();
  } break;
  case SSM_MAGIC_ENDIAN: {
    // endian
    unimplemented();
  } break;
  case SSM_MAGIC_VERSION: {
    // version
    unimplemented();
  } break;
  }
  unimplemented();
  NEXT(1);
}
OP(XFN) {
  register uint16_t argc = read_uint16_t(ip + 1);
  register uint16_t stack_size = read_uint16_t(ip + 3);
  unimplemented();
  NEXT(5);
}
OP(HEADER) {
  register uint32_t version = read_uint32_t(ip + 1);
  register uint32_t chunk_size = read_uint32_t(ip + 5);
  register uint32_t global_offset = read_uint32_t(ip + 9);
  register uint32_t global_count = read_uint32_t(ip + 13);
  unimplemented();
  NEXT(17);
}
